### ISSUE TITLE
Error: Class fielder does not exist (ReflectionException)

### ISSUE THREAD

**Issue by Soean** [assely/fielder#6]
I start with a clean Assely Installation with the the Fielder plugin. 
I add a Metabox and a Fielder Textfield with the steps from the docu.

Now I get this error
**Fatal error: Uncaught ReflectionException: Class fielder does not exist in /.../wp-content/plugins/assely-framework/vendor/illuminate/container/Container.php on line 749**

**Comment by jedrzejchalubek** [comment]
Probably, you forgotten to register `FielderServiceProvider` in `config/app.php` file.

```php
/**
 * Assely Framework Service Providers
 */
Assely\Foundation\Providers\FoundationServiceProvider::class,

Assely\Fielder\FielderServiceProvider::class, // <--- this one

/**
 * Application Service Providers
 */
App\Providers\AppServiceProvider::class,
App\Providers\ConsoleServiceProvider::class,
App\Providers\HttpServiceProvider::class,
App\Providers\SingularityServiceProvider::class,
```

**Comment by jedrzejchalubek** [comment]
Have to find a way to inform about that in a more friendly way.

**Comment by Soean** [comment]
No, I added the provider and alias

**Comment by jedrzejchalubek** [comment]
It is important to register `FielderServiceProvider` before `App\Providers\*` providers, because `SingularityServiceProvider` registers all singularities (and they fields) on bootstraping.

**Comment by Soean** [comment]
Thanks, that was the problem :)

**Comment by jedrzejchalubek** [comment]
and that one must be better described in documentation too. Going to keep this open :)

- [ ] Find a way to display friendly error message when `Field` facade is used, but FielderServiceProvider not been registered
- [ ] Inform in documentation about registering `FielderServiceProvider` before `App\Providers`
